- name: Prepare packaging variables
  contrail_packaging:
    zuul: "{{ zuul }}"

- set_fact:
    executor_sandbox_path: "{{ zuul.executor.work_root }}/{{ packaging.target_dir }}"
  delegate_to: localhost

- name: create sandbox root dir
  file:
    path: "{{ executor_sandbox_path }}"
    state: directory
  delegate_to: localhost

- name: copy scripts
  copy:
    src: "{{ item }}"
    dest: "{{ executor_sandbox_path }}"
    mode: preserve
  with_items:
    - repo
    - manifest_translator.py
  delegate_to: localhost

- name: repo init
  command: ./repo init -u https://github.com/Juniper/contrail-vnc
  args:
    chdir: "{{ executor_sandbox_path }}"
  delegate_to: localhost

- name: dump zuul variables to a file
  copy:
    content: "{{ zuul }}"
    dest: "{{ executor_sandbox_path }}/zuul_var.yaml"
  delegate_to: localhost

- name: apply changes to the manifest.xml
  command: ./manifest_translator.py ./zuul_var.yaml {{ executor_sandbox_path }}/.repo/manifest.xml
  args:
    chdir: "{{ executor_sandbox_path }}"
  delegate_to: localhost

- name: repo sync
  command: ./repo sync
  args:
    chdir: "{{ executor_sandbox_path }}"
  delegate_to: localhost

- name: Clean-up auxiliary repo files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - repo
    - manifest_translator.py
    - zuul_var.yaml

- name: send the sandbox to the worker node
  synchronize:
    src: "{{ executor_sandbox_path }}"
    dest: "{{ ansible_env.HOME }}"

