- name: Download dummy package
  get_url:
    url: http://ftp.us.debian.org/debian/pool/main/t/tzdata/tzdata_2017b-1_all.deb
    dest: /tmp/tzdata.deb
- name: Create Aptly repo
  uri:
    url: http://1.1.1.59/api/repos
    method: POST
    user: aptly
    password: aptlypassword
    body: '{ "Name": "{{ reponame }}" }'
    force_basic_auth: yes
    body_format: json
    status_code: 201
