- name: Download dummy package
  get_url:
    url: http://ftp.us.debian.org/debian/pool/main/t/tzdata/tzdata_2017b-1_all.deb
    dest: /tmp/tzdata.deb
- name: Create Aptly repo
  uri:
    url: http://1.1.1.59/api/repos
    method: POST
    user: aptly
    password: aptlypassword
    body: '{ "Name": "{{ reponame }}" }'
    force_basic_auth: yes
    body_format: json
    status_code: 201
- name: add packages to repo
  uri:
    url: http://1.1.1.59/api/repos/{{ reponame }}/files/{{ reponame }}
    method: POST
    user: aptly
    password: aptlypassword
    body: '{ "Name": "{{ reponame }}" }'
    force_basic_auth: yes
    body_format: json
    status_code: 201
- name: publish repo
  uri:
    url: http://1.1.1.59/api/publish
    method: POST
    user: aptly
    password: aptlypassword
    body: '{ "SourceKind": "local", "Sources": [{"Name": "{{ reponame }}"}], "Architectures": ["amd64"] }'
    force_basic_auth: yes
    body_format: json
    status_code: 201
