- name: Verify connectivity to review.opencontrail.org
  wait_for:
    host: review.opencontrail.org
    port: 443
    timeout: 10

- name: upload packages
  synchronize:
    src: "{{ src_dir }}"
    dest: /var/lib/aptly/upload/{{ reponame }}/
    mode: pull
    rsync_opts:
      - '--rsh="ssh -l aptly"'
  delegate_to: "1.1.1.59"
