- file:
    path: /tmp/jobs/{{ reponame }}
    state: directory
    mode: 0755
    delegate_to: '127.0.0.1'
- name: upload packages
  synchronize:
    src: "/tmp/*.deb"
    dest: /tmp/jobs/{{ reponame }}/
    mode:  pull
