- file:
    path: /tmp/jobs/{{ reponame }}
    state: directory
    mode: 0755
- name: upload packages
  synchronize:
    src: "/tmp/*.deb"
    dest: /tmp/jobs/{{ reponame }}/
    rsync_opts:
      - '--rsh="ssh -l aptly"'
  delegate_to: "127.0.0.1"
